// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDanVAsWM5_lJ-b2LOCshGCYn1WeMMTzMs',
    appId: '1:943466815206:web:23d408cc265bf5ab91a527',
    messagingSenderId: '943466815206',
    projectId: 'order-in-the-court-6f9e0',
    authDomain: 'order-in-the-court-6f9e0.firebaseapp.com',
    storageBucket: 'order-in-the-court-6f9e0.firebasestorage.app',
    measurementId: 'G-SVG6VTJCC2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgs4w5ggeGbI5UJZgD4jVRvYN2ndhwwLI',
    appId: '1:943466815206:android:ce1352fe3bd87bf591a527',
    messagingSenderId: '943466815206',
    projectId: 'order-in-the-court-6f9e0',
    storageBucket: 'order-in-the-court-6f9e0.firebasestorage.app',
  );
}
